language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: 
  - pip install coveralls
  - pip install -e . --use-mirrors
# command to run tests
script: 
  - coverage run --source=ascii_graph setup.py test
after_success:
  - coveralls
