language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - pip install coveralls
  - pip install -e .
# command to run tests
script: 
  - coverage run --source=ascii_graph setup.py test || python setup.py test
after_success:
  - coveralls
